### ISSUE TITLE
Capacitive buttons light is always on

### ISSUE THREAD

**Issue by itzik2sh** [teamacid/android_kernel_galaxys4gmtd#15] opened 2012-07-13 03:49 UTC
As long as screen is open, capacitive buttons light is always on and very bright.
there are some apps in the Google Play to dim it, but they don't work.
It exists on all our MTD ROMs so I guess it is kernel related.

**Comment by fbis251** [comment] 2012-07-13 03:50
This is a duplicate of
https://github.com/teamacid/android_device_samsung_galaxys4gmtd/issues/14

Admittedly it probably belongs in the kernel and not just in the device tree.

**Comment by fbis251** [comment] 2012-07-13 04:24
Re-opened the issue after closing the device tree one.

**Closed as completed** 2018-12-10 16:51 UTC
Labels: bug, GB, ICS
